"""Add password reset token table and rate limiting fields to user

Revision ID: 34bd6356fba6
Revises: e7f2d5c4a1b6
Create Date: 2026-03-12 00:08:40.232478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34bd6356fba6'
down_revision: Union[str, None] = 'e7f2d5c4a1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_created_at'), 'password_reset_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_tenant_id'), 'password_reset_tokens', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.drop_index('ix_shift_record_tenant_date', table_name='shift_record')
    op.drop_index('ix_shift_record_tenant_employee_date', table_name='shift_record')
    op.drop_constraint('uq_shift_record_roster', 'shift_record', type_='unique')
    op.create_index(op.f('ix_shift_record_created_at'), 'shift_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_shift_record_date'), 'shift_record', ['date'], unique=False)
    op.alter_column('team', 'shift_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('time_record', 'clock_in_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('time_record', 'clock_out_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('time_record', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('time_record', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index('idx_time_record_employee_date', table_name='time_record')
    op.drop_index('uq_active_clock_in', table_name='time_record', postgresql_where='(clock_out_timestamp IS NULL)')
    op.add_column('user', sa.Column('last_password_reset_request_at', sa.DateTime(), nullable=True))
    # Add column as nullable first
    op.add_column('user', sa.Column('password_reset_attempt_count', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute('UPDATE "user" SET password_reset_attempt_count = 0 WHERE password_reset_attempt_count IS NULL')
    # Make column NOT NULL
    op.alter_column('user', 'password_reset_attempt_count', existing_type=sa.Integer(), nullable=False)
    op.alter_column('user', 'password_reset_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_login',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'password_reset_expires',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('user', 'password_reset_attempt_count', existing_type=sa.Integer(), nullable=True)
    op.drop_column('user', 'password_reset_attempt_count')
    op.drop_column('user', 'last_password_reset_request_at')
    op.create_index('uq_active_clock_in', 'time_record', ['tenant_id', 'employee_id', 'date'], unique=True, postgresql_where='(clock_out_timestamp IS NULL)')
    op.create_index('idx_time_record_employee_date', 'time_record', ['tenant_id', 'employee_id', sa.text('date DESC')], unique=False)
    op.alter_column('time_record', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('time_record', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('time_record', 'clock_out_timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('time_record', 'clock_in_timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('team', 'shift_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_shift_record_date'), table_name='shift_record')
    op.drop_index(op.f('ix_shift_record_created_at'), table_name='shift_record')
    op.create_unique_constraint('uq_shift_record_roster', 'shift_record', ['tenant_id', 'employee_id', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_shift_record_tenant_employee_date', 'shift_record', ['tenant_id', 'employee_id', 'date'], unique=False)
    op.create_index('ix_shift_record_tenant_date', 'shift_record', ['tenant_id', 'date'], unique=False)
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_tenant_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_created_at'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
