"""Create time_entry table for automatic shift-based time tracking

Revision ID: 79ad9726ce5e
Revises: 34bd6356fba6
Create Date: 2026-03-13 20:27:53.642249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79ad9726ce5e'
down_revision: Union[str, None] = '34bd6356fba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('source', sa.Enum('SHIFT', 'MANUAL', name='timeentrysource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('shift_record_id', sa.Uuid(), nullable=True),
    sa.Column('shift_type_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['shift_record_id'], ['shift_record.id'], ),
    sa.ForeignKeyConstraint(['shift_type_id'], ['shift_type.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'shift_date', 'shift_type_id', name='uq_time_entry_employee_date_shift')
    )
    op.create_index(op.f('ix_time_entries_employee_id'), 'time_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_time_entries_shift_date'), 'time_entries', ['shift_date'], unique=False)
    op.create_index(op.f('ix_time_entries_tenant_id'), 'time_entries', ['tenant_id'], unique=False)
    # Composite indexes for common query patterns
    op.create_index('ix_time_entries_tenant_employee_date', 'time_entries', ['tenant_id', 'employee_id', 'shift_date'], unique=False)
    op.create_index('ix_time_entries_tenant_date', 'time_entries', ['tenant_id', 'shift_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_entries_tenant_date', table_name='time_entries')
    op.drop_index('ix_time_entries_tenant_employee_date', table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_tenant_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_shift_date'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_employee_id'), table_name='time_entries')
    op.drop_table('time_entries')
    # ### end Alembic commands ###
