"""integrate_shift_types_with_teams

Revision ID: 9db3d4f10fe2
Revises: 2aca5d9f21d0
Create Date: 2026-02-28 09:25:24.161298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9db3d4f10fe2'
down_revision: Union[str, None] = '2aca5d9f21d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_type', 'time_windows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('shift_type', 'expected_hours',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_shift_type_tenant_id'), 'shift_type', ['tenant_id'], unique=False)
    op.drop_constraint('shift_type_tenant_id_fkey', 'shift_type', type_='foreignkey')
    op.create_foreign_key('shift_type_tenant_id_fkey', 'shift_type', 'tenant', ['tenant_id'], ['id'])
    op.add_column('team', sa.Column('shift_type_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_team_shift_type_id'), 'team', ['shift_type_id'], unique=False)
    op.create_foreign_key('team_shift_type_id_fkey', 'team', 'shift_type', ['shift_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_type', 'time_windows',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('shift_type', 'expected_hours',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_shift_type_tenant_id'), table_name='shift_type')
    op.drop_constraint('shift_type_tenant_id_fkey', 'shift_type', type_='foreignkey')
    op.create_foreign_key('shift_type_tenant_id_fkey', 'shift_type', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_shift_type_id_fkey', 'team', type_='foreignkey')
    op.drop_index(op.f('ix_team_shift_type_id'), table_name='team')
    op.drop_column('team', 'shift_type_id')
    op.add_column('team', sa.Column('shift_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('team', sa.Column('shift_start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('team', sa.Column('shift_end', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
